#!/bin/bash

# GitHub to Azure DevOps Token Setup Script
# This script helps you set up the connection from GitHub to Azure DevOps

set -e

echo "🔑 GitHub to Azure DevOps Token Setup"
echo "===================================="

# Configuration
GITHUB_REPO="RudrakshSingh/etelios"
AZURE_DEVOPS_ORG="Hindempire-devops1"
AZURE_DEVOPS_PROJECT="etelios"

echo "📋 Configuration:"
echo "  GitHub Repository: $GITHUB_REPO"
echo "  Azure DevOps Org: $AZURE_DEVOPS_ORG"
echo "  Azure DevOps Project: $AZURE_DEVOPS_PROJECT"
echo ""

echo "🔑 Step 1: Generate Azure DevOps Token"
echo "======================================"
echo "1. Go to: https://dev.azure.com/$AZURE_DEVOPS_ORG/_usersSettings/tokens"
echo "2. Click 'New Token'"
echo "3. Name: 'GitHub Integration'"
echo "4. Organization: $AZURE_DEVOPS_ORG"
echo "5. Expiration: 1 year"
echo "6. Scopes: ✅ All scopes (Full access)"
echo "7. Click 'Create'"
echo "8. Copy the token (save it securely!)"
echo ""

echo "🔧 Step 2: Add Token to GitHub Secrets"
echo "======================================"
echo "1. Go to: https://github.com/$GITHUB_REPO/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Name: 'AZURE_DEVOPS_TOKEN'"
echo "4. Value: [paste your token here]"
echo "5. Click 'Add secret'"
echo ""

echo "🚀 Step 3: Test the Connection"
echo "============================="
echo "1. Go to GitHub Actions: https://github.com/$GITHUB_REPO/actions"
echo "2. Look for 'Azure DevOps CI/CD Pipeline' workflow"
echo "3. Check if it runs successfully"
echo ""

echo "📊 Step 4: Verify Azure DevOps"
echo "============================="
echo "1. Go to: https://dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT"
echo "2. Check if repository is created"
echo "3. Verify code is pushed"
echo ""

echo "🔧 Alternative: Use GitHub CLI"
echo "=============================="
echo "If you have GitHub CLI installed:"
echo ""
echo "# Install GitHub CLI (if not installed)"
echo "brew install gh"
echo ""
echo "# Login to GitHub"
echo "gh auth login"
echo ""
echo "# Add secret via CLI"
echo "gh secret set AZURE_DEVOPS_TOKEN --body \"your-token-here\""
echo ""

echo "✅ Success Checklist:"
echo "===================="
echo "[ ] Azure DevOps token generated"
echo "[ ] Token added to GitHub secrets"
echo "[ ] GitHub Actions workflow runs"
echo "[ ] Code pushed to Azure DevOps"
echo "[ ] Azure DevOps repository created"
echo ""

echo "🚨 Troubleshooting:"
echo "=================="
echo "1. Token generation fails:"
echo "   - Check Azure DevOps login"
echo "   - Verify permissions"
echo "   - Try different scopes"
echo ""
echo "2. GitHub secret addition fails:"
echo "   - Check repository permissions"
echo "   - Use GitHub CLI instead"
echo "   - Verify admin access"
echo ""
echo "3. Connection still fails:"
echo "   - Verify token is correct"
echo "   - Check Azure DevOps repository exists"
echo "   - Review GitHub Actions logs"
echo ""

echo "📚 Documentation:"
echo "==============="
echo "- GITHUB-AZURE-DEVOPS-TOKEN-GUIDE.md"
echo "- AZURE-DEVOPS-SETUP-GUIDE.md"
echo "- AZURE-DEVOPS-QUICK-FIX.md"
