apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-service
  labels:
    app: hr-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-service
  template:
    metadata:
      labels:
        app: hr-service
    spec:
      containers:
      - name: hr-service
        image: ghcr.io/rudrakshsingh/etelios/hr-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/hrms"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hr-service
  labels:
    app: hr-service
spec:
  selector:
    app: hr-service
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP
